//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPathTutor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XPathTutor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1 style=&quot;color: #5e9ca0;&quot;&gt;Welcome to the &lt;span style=&quot;color: #2b2301;&quot;&gt;XPATH Tutorial&lt;/span&gt;&lt;/h1&gt;
        ///&lt;h2 style=&quot;color: #2e6c80;&quot;&gt;Scope of this tutorial&lt;/h2&gt;
        ///&lt;div&gt;
        ///  &lt;p&gt;&lt;b&gt;This tutorial is aimed at giving you the overall knowledge of XPath.&lt;/b&gt; &lt;p&gt;
        ///  &lt;p&gt;&lt;b&gt;You will learn the how to write an XPath expressions&lt;/b&gt;.&lt;/p&gt;
        ///  &lt;p&gt;&lt;b&gt;You will learn to use different operators in XPath.&lt;/b&gt;&lt;/p&gt;
        ///  &lt;p&gt;&lt;b&gt;Learn to parse through XML to get your data.&lt;/b&gt;&lt;/p&gt;
        /// &lt;/div&gt;
        ///&lt;h2 style=&quot;color: #2e6c80;&quot;&gt;Instructions:&lt;/h2&gt;
        ///&lt;u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1 style=&quot;color: #5e9ca0;&quot;&gt;Welcome to the &lt;span style=&quot;color: #2b2301;&quot;&gt;XPATH Tutorial&lt;/span&gt;&lt;/h1&gt;
        ///&lt;h2 style=&quot;color: #2e6c80;&quot;&gt;Scope of this tutorial&lt;/h2&gt;
        ///&lt;div&gt;
        ///  &lt;p&gt;&lt;b&gt;This tutorial is aimed at giving you the overall knowledge of XPath.&lt;/b&gt; &lt;p&gt;
        ///  &lt;p&gt;&lt;b&gt;You will learn the how to write an XPath expressions&lt;/b&gt;.&lt;/p&gt;
        ///  &lt;p&gt;&lt;b&gt;You will learn to use different operators in XPath.&lt;/b&gt;&lt;/p&gt;
        ///  &lt;p&gt;&lt;b&gt;Learn to parse through XML to get your data.&lt;/b&gt;&lt;/p&gt;
        /// &lt;/div&gt;
        ///&lt;h2 style=&quot;color: #2e6c80;&quot;&gt;Instructions:&lt;/h2&gt;
        ///&lt;u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Index1 {
            get {
                return ResourceManager.GetString("Index1", resourceCulture);
            }
        }
    }
}
